const SIGN_IN_STATE = 'SIGN_IN_STATE';
const SIGN_UP_STATE = 'SIGN_UP_STATE';
const FORGOT_PASSWORD_STATE = 'FORGOT_PASSWORD_STATE';
const NEW_PASSWORD_STATE = 'NEW_PASSWORD_STATE';

const SIGN_IN_TEXT = 'Sign In';
const SIGN_UP_TEXT = 'Sign Up';
const FORGOT_PASSWORD_TEXT = 'Reset password';
const NEW_PASSWORD_TEXT = 'Create new password';

export {
    SIGN_IN_STATE,
    SIGN_UP_STATE,
    SIGN_IN_TEXT,
    SIGN_UP_TEXT,
    FORGOT_PASSWORD_STATE,
    FORGOT_PASSWORD_TEXT,
    NEW_PASSWORD_STATE,
    NEW_PASSWORD_TEXT
};