const OFFER_NAME = 'OFFER_NAME'
const TOTAL_PRICE = 'TOTAL_PRICE'
const BOOSTER_PRICE = 'BOOSTER_PRICE'
const GAME_NAME = 'GAME_NAME'
const GAME_PLATFORM = 'GAME_PLATFORM'

export {OFFER_NAME, TOTAL_PRICE, BOOSTER_PRICE, GAME_NAME, GAME_PLATFORM}

